<!DOCTYPE html><html lang="pt-BR">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Tech by Duda</title>
  <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@400;600&display=swap" rel="stylesheet">
  <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
  <style>
    :root {
      --bg: #f9f9f9;
      --text: #2c3e50;
      --primary: #8E44AD;
      --secondary: #AED6F1;
      --card: #fff;
      --hover: #732d91;
    }@media (prefers-color-scheme: dark) {
  :root {
    --bg: #1e1e2f;
    --text: #ecf0f1;
    --primary: #9b59b6;
    --secondary: #3498db;
    --card: #2c3e50;
    --hover: #a569bd;
  }
}

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: 'Quicksand', sans-serif;
}

body {
  background: var(--bg);
  color: var(--text);
  line-height: 1.6;
  scroll-behavior: smooth;
}

header {
  background: linear-gradient(135deg, var(--primary), var(--secondary));
  color: #fff;
  padding: 4rem 2rem;
  text-align: center;
  animation: fadeIn 1s ease-in-out;
}

header h1 {
  font-size: 2.5rem;
}

header p {
  font-size: 1.2rem;
  margin-top: 0.5rem;
}

section {
  padding: 3rem 2rem;
  max-width: 900px;
  margin: 0 auto;
  opacity: 0;
  transform: translateY(30px);
  animation: slideUp 0.6s ease forwards;
}

h2 {
  font-size: 2rem;
  color: var(--primary);
  margin-bottom: 1rem;
}

.projects {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: 1.5rem;
}

.project-card {
  background: var(--card);
  border-radius: 10px;
  padding: 1.5rem;
  box-shadow: 0 2px 10px rgba(0,0,0,0.1);
  transition: transform 0.3s, box-shadow 0.3s;
}

.project-card:hover {
  transform: translateY(-5px);
  box-shadow: 0 4px 20px rgba(0,0,0,0.2);
}

.contact {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.contact a {
  color: #fff;
  background: var(--primary);
  padding: 0.75rem 1.5rem;
  border-radius: 8px;
  text-decoration: none;
  text-align: center;
  transition: background 0.3s;
}

.contact a:hover {
  background: var(--hover);
}

@keyframes slideUp {
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

@keyframes fadeIn {
  from {
    opacity: 0;
  } to {
    opacity: 1;
  }
}

  </style>
</head>
<body>
  <header>
    <h1>Tech by Duda</h1>
    <p>Criando soluções com criatividade, código e coragem.</p>
  </header>  <section style="animation-delay: 0.2s;">
    <h2>Sobre mim</h2>
    <p>Sou Maria Eduarda — ou só Duda mesmo. Curiosa por natureza, programadora por paixão e criativa por essência. Aqui você vai conhecer um pouco do que eu crio quando misturo tecnologia, sonhos e atitude.</p>
  </section>  <section style="animation-delay: 0.4s;">
    <h2>Projetos</h2>
    <div class="projects" id="github-projects">
      <p>Carregando projetos do GitHub...</p>
    </div>
  </section>  <section style="animation-delay: 0.6s;">
    <h2><i class="fab fa-linkedin"></i> LinkedIn</h2>
    <p>Quer ver mais sobre minha jornada profissional?</p>
    <a class="contact" href="https://linkedin.com/in/mariaeduardacampos20" target="_blank">Acessar meu LinkedIn</a>
  </section>  <section style="animation-delay: 0.8s;">
    <h2><i class="fas fa-envelope"></i> Contato</h2>
    <div class="contact">
      <a href="https://wa.me/5599999999999" target="_blank">Falar comigo no WhatsApp</a>
      <a href="mailto:mariaeduarda@email.com">Me enviar um e-mail</a>
    </div>
  </section>  <script>
    // Fetch GitHub Repos
    fetch("https://api.github.com/users/MariaEduardaCampos20/repos")
      .then(response => response.json())
      .then(data => {
        const container = document.getElementById("github-projects");
        container.innerHTML = "";
        const topRepos = data.slice(0, 6); // Mostra os 6 primeiros
        topRepos.forEach(repo => {
          const card = document.createElement("div");
          card.className = "project-card";
          card.innerHTML = `
            <h3>${repo.name}</h3>
            <p>${repo.description || 'Sem descrição disponível.'}</p>
            <a href="${repo.html_url}" target="_blank">Ver no GitHub</a>
          `;
          container.appendChild(card);
        });
      })
      .catch(error => {
        document.getElementById("github-projects").innerHTML = "Erro ao carregar projetos.";
      });
  </script></body>
</html><!DOCTYPE html><html lang="pt-BR">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Tech by Duda</title>
  <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@400;600&display=swap" rel="stylesheet">
  <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
  <style>
    :root {
      --bg: #f9f9f9;
      --text: #2c3e50;
      --primary: #8E44AD;
      --secondary: #AED6F1;
      --card: #fff;
      --hover: #732d91;
    }@media (prefers-color-scheme: dark) {
  :root {
    --bg: #1e1e2f;
    --text: #ecf0f1;
    --primary: #9b59b6;
    --secondary: #3498db;
    --card: #2c3e50;
    --hover: #a569bd;
  }
}

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: 'Quicksand', sans-serif;
}

body {
  background: var(--bg);
  color: var(--text);
  line-height: 1.6;
  scroll-behavior: smooth;
}

header {
  background: linear-gradient(135deg, var(--primary), var(--secondary));
  color: #fff;
  padding: 4rem 2rem;
  text-align: center;
  animation: fadeIn 1s ease-in-out;
}

header h1 {
  font-size: 2.5rem;
}

header p {
  font-size: 1.2rem;
  margin-top: 0.5rem;
}

section {
  padding: 3rem 2rem;
  max-width: 900px;
  margin: 0 auto;
  opacity: 0;
  transform: translateY(30px);
  animation: slideUp 0.6s ease forwards;
}

h2 {
  font-size: 2rem;
  color: var(--primary);
  margin-bottom: 1rem;
}

.projects {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: 1.5rem;
}

.project-card {
  background: var(--card);
  border-radius: 10px;
  padding: 1.5rem;
  box-shadow: 0 2px 10px rgba(0,0,0,0.1);
  transition: transform 0.3s, box-shadow 0.3s;
}

.project-card:hover {
  transform: translateY(-5px);
  box-shadow: 0 4px 20px rgba(0,0,0,0.2);
}

.contact {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.contact a {
  color: #fff;
  background: var(--primary);
  padding: 0.75rem 1.5rem;
  border-radius: 8px;
  text-decoration: none;
  text-align: center;
  transition: background 0.3s;
}

.contact a:hover {
  background: var(--hover);
}

@keyframes slideUp {
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

@keyframes fadeIn {
  from {
    opacity: 0;
  } to {
    opacity: 1;
  }
}

  </style>
</head>
<body>
  <header>
    <h1>Tech by Duda</h1>
    <p>Criando soluções com criatividade, código e coragem.</p>
  </header>  <section style="animation-delay: 0.2s;">
    <h2>Sobre mim</h2>
    <p>Sou Maria Eduarda — ou só Duda mesmo. Curiosa por natureza, programadora por paixão e criativa por essência. Aqui você vai conhecer um pouco do que eu crio quando misturo tecnologia, sonhos e atitude.</p>
  </section>  <section style="animation-delay: 0.4s;">
    <h2>Projetos</h2>
    <div class="projects" id="github-projects">
      <p>Carregando projetos do GitHub...</p>
    </div>
  </section>  <section style="animation-delay: 0.6s;">
    <h2><i class="fab fa-linkedin"></i> LinkedIn</h2>
    <p>Quer ver mais sobre minha jornada profissional?</p>
    <a class="contact" href="https://linkedin.com/in/mariaeduardacampos20" target="_blank">Acessar meu LinkedIn</a>
  </section>  <section style="animation-delay: 0.8s;">
    <h2><i class="fas fa-envelope"></i> Contato</h2>
    <div class="contact">
      <a href="https://wa.me/5599999999999" target="_blank">Falar comigo no WhatsApp</a>
      <a href="mailto:mariaeduarda@email.com">Me enviar um e-mail</a>
    </div>
  </section>  <script>
    // Fetch GitHub Repos
    fetch("https://api.github.com/users/MariaEduardaCampos20/repos")
      .then(response => response.json())
      .then(data => {
        const container = document.getElementById("github-projects");
        container.innerHTML = "";
        const topRepos = data.slice(0, 6); // Mostra os 6 primeiros
        topRepos.forEach(repo => {
          const card = document.createElement("div");
          card.className = "project-card";
          card.innerHTML = `
            <h3>${repo.name}</h3>
            <p>${repo.description || 'Sem descrição disponível.'}</p>
            <a href="${repo.html_url}" target="_blank">Ver no GitHub</a>
          `;
          container.appendChild(card);
        });
      })
      .catch(error => {
        document.getElementById("github-projects").innerHTML = "Erro ao carregar projetos.";
      });
  </script></body>
</html>
